/**
 * Output Spec §5.2 — tokens.css (CSS Variables) 생성.
 *
 * Seed → Map → Alias 순서로 :root 변수를 펼친다.
 * Alias 토큰은 reference 형태(`{map.color.primary.default}`)를 var(--xds-*) 참조로 변환.
 */

import { resolveTokenRef } from "../tokens/build";
import {
  COLOR_SCALE_STEPS,
  SEMANTIC_COLORS,
  type ColorScaleStep,
  type SemanticState,
  type TokenTree,
} from "../tokens/types";
import { GENERATOR_VERSION } from "../version";

const SEMANTIC_STATES: SemanticState[] = [
  "bg",
  "bgHover",
  "border",
  "borderHover",
  "hover",
  "default",
  "active",
  "text",
  "textHover",
  "textActive",
];

interface CssGenOptions {
  /** 헤더 주석 — Output Spec §1.1 read-only 원칙 */
  projectName?: string;
  projectVersion?: string;
  /** Alias의 reference 문자열을 var(--xds-*)로 변환할지 (기본 true) */
  resolveAliasAsVar?: boolean;
}

export function tokenTreeToCss(tree: TokenTree, opts: CssGenOptions = {}): string {
  const lines: string[] = [];
  const projectName = opts.projectName ?? tree.meta.presetId;
  const projectVersion = opts.projectVersion ?? "1.0.0";
  const resolveAliasAsVar = opts.resolveAliasAsVar ?? true;

  lines.push(
    `/* GENERATED BY XDS Generator v${GENERATOR_VERSION} — DO NOT EDIT MANUALLY */`,
  );
  lines.push(
    `/* ${projectName} Design System v${projectVersion} — ${tree.meta.derivedAt.slice(0, 10)} */`,
  );
  lines.push("");
  lines.push(":root {");

  // Seed
  lines.push("  /* Seed — 디자이너 직접 결정 13종 */");
  lines.push(`  --xds-seed-color-primary: ${tree.seed.color.primary};`);
  lines.push(`  --xds-seed-color-success: ${tree.seed.color.success};`);
  lines.push(`  --xds-seed-color-warning: ${tree.seed.color.warning};`);
  lines.push(`  --xds-seed-color-error: ${tree.seed.color.error};`);
  lines.push(`  --xds-seed-color-info: ${tree.seed.color.info};`);
  lines.push(`  --xds-seed-color-bg-base: ${tree.seed.color.bgBase};`);
  lines.push(`  --xds-seed-color-text-base: ${tree.seed.color.textBase};`);
  lines.push(`  --xds-seed-border-radius: ${tree.seed.borderRadius}px;`);
  lines.push(`  --xds-seed-font-size: ${tree.seed.fontSize}px;`);
  lines.push(
    `  --xds-seed-font-family: ${tree.seed.fontFamily.map(quoteIfNeeded).join(", ")};`,
  );
  lines.push(`  --xds-seed-spacing-base: ${tree.seed.spacingBase}px;`);
  // 선택적 seed override(라벨 색)는 정의된 경우에만 emit.
  if (tree.seed.onPrimaryColor) {
    lines.push(`  --xds-seed-on-primary-color: ${tree.seed.onPrimaryColor};`);
  }
  if (tree.seed.onDangerColor) {
    lines.push(`  --xds-seed-on-danger-color: ${tree.seed.onDangerColor};`);
  }
  lines.push("");

  // Map — Color Scale
  lines.push("  /* Map — 시맨틱 색 6종 × 11단 스케일 (자동 파생) */");
  for (const color of SEMANTIC_COLORS) {
    for (const step of COLOR_SCALE_STEPS) {
      const value = tree.map.color[color][step as ColorScaleStep];
      lines.push(`  --xds-color-${color}-${step}: ${value};`);
    }
  }
  lines.push("");

  // Map — Semantic states
  lines.push("  /* Map — 시맨틱 상태 변형 (named steps) */");
  for (const color of SEMANTIC_COLORS) {
    for (const state of SEMANTIC_STATES) {
      const value = tree.map.color[color][state];
      lines.push(`  --xds-color-${color}-${kebab(state)}: ${value};`);
    }
  }
  lines.push("");

  // Map — Size·Radius·Font
  lines.push("  /* Map — Sizing */");
  for (const [k, v] of Object.entries(tree.map.size)) {
    lines.push(`  --xds-size-${kebab(k)}: ${v}px;`);
  }
  lines.push("");

  lines.push("  /* Map — Radius */");
  for (const [k, v] of Object.entries(tree.map.radius)) {
    lines.push(`  --xds-radius-${kebab(k)}: ${v}px;`);
  }
  lines.push("");

  lines.push("  /* Map — Typography */");
  for (const [k, v] of Object.entries(tree.map.font.size)) {
    lines.push(`  --xds-font-size-${kebab(k)}: ${v}px;`);
  }
  for (const [k, v] of Object.entries(tree.map.font.lineHeight)) {
    lines.push(`  --xds-line-height-${kebab(k)}: ${v};`);
  }
  for (const [k, v] of Object.entries(tree.map.font.letterSpacing)) {
    lines.push(`  --xds-letter-spacing-${kebab(k)}: ${v};`);
  }
  lines.push("");

  // Alias
  lines.push("  /* Alias — 컴포넌트 참조 의미 토큰 */");
  emitAliasGroup(lines, "text", tree.alias.text, tree, resolveAliasAsVar);
  emitAliasGroup(lines, "surface", tree.alias.surface, tree, resolveAliasAsVar);
  emitAliasGroup(lines, "border", tree.alias.border, tree, resolveAliasAsVar);
  emitAliasGroup(lines, "action", tree.alias.action, tree, resolveAliasAsVar);
  emitAliasGroup(lines, "feedback", tree.alias.feedback, tree, resolveAliasAsVar);
  lines.push(`  --xds-control-height-sm: ${tree.alias.control.height.sm}px;`);
  lines.push(`  --xds-control-height-md: ${tree.alias.control.height.md}px;`);
  lines.push(`  --xds-control-height-lg: ${tree.alias.control.height.lg}px;`);
  lines.push(`  --xds-control-padding-x: ${tree.alias.control.padding.x}px;`);
  lines.push(`  --xds-focus-ring-width: ${tree.alias.focus.ring.width}px;`);
  lines.push(`  --xds-focus-ring-offset: ${tree.alias.focus.ring.offset}px;`);
  lines.push(
    `  --xds-focus-ring-color: ${refToVar(tree.alias.focus.ring.color, tree, resolveAliasAsVar)};`,
  );

  lines.push("}");
  lines.push("");

  // prefers-reduced-motion (Accessibility Spec O-12)
  lines.push("@media (prefers-reduced-motion: reduce) {");
  lines.push("  :root {");
  lines.push("    --xds-duration-fast: 0ms;");
  lines.push("    --xds-duration-normal: 0ms;");
  lines.push("    --xds-duration-slow: 0ms;");
  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}

function emitAliasGroup<T extends Record<string, string>>(
  lines: string[],
  group: string,
  aliasGroup: T,
  tree: TokenTree,
  resolve: boolean,
): void {
  for (const [k, v] of Object.entries(aliasGroup)) {
    lines.push(`  --xds-${group}-${kebab(k)}: ${refToVar(v, tree, resolve)};`);
  }
}

function refToVar(ref: string, tree: TokenTree, resolve: boolean): string {
  const match = ref.match(/^\{([^}]+)\}$/);
  if (!match) return ref;
  if (!resolve) return ref;
  const path = match[1];
  // Map 색 참조 → var(--xds-color-<color>-<key>) 체인
  if (path.startsWith("map.color.")) {
    const segments = path.slice("map.color.".length).split(".");
    const [color, key] = segments;
    return `var(--xds-color-${color}-${kebab(key)})`;
  }
  // Seed 색 참조 → 선언된 --xds-seed-color-* 변수로 체인
  if (path.startsWith("seed.color.")) {
    const key = path.slice("seed.color.".length);
    return `var(--xds-seed-color-${kebab(key)})`;
  }
  // Seed 라벨 색 직접 참조 (onPrimaryColor / onDangerColor)
  if (path === "seed.onPrimaryColor") return `var(--xds-seed-on-primary-color)`;
  if (path === "seed.onDangerColor") return `var(--xds-seed-on-danger-color)`;
  // 그 외 (수치 등)는 직접 해석
  return resolveTokenRef(ref, tree);
}

function kebab(s: string): string {
  return s.replace(/([A-Z])/g, "-$1").toLowerCase();
}

function quoteIfNeeded(family: string): string {
  return /^[a-zA-Z][a-zA-Z0-9-]*$/.test(family) ? family : `"${family}"`;
}
