/**
 * Output Spec §4 — README.md 템플릿 생성.
 */

import type { TokenTree } from "../tokens/types";
import { GENERATOR_VERSION } from "../version";

interface Ctx {
  tree: TokenTree;
  projectName: string;
  projectVersion: string;
  projectType: string;
  filenameSuffix: string;
}

export function buildReadme(ctx: Ctx): string {
  const { tree, projectName, projectVersion, projectType, filenameSuffix } = ctx;
  return [
    `# ${projectName} Design System`,
    "",
    `> Generated by XDS Generator v${GENERATOR_VERSION} on ${tree.meta.derivedAt}`,
    `> Project type: ${projectType}`,
    `> Style preset: ${tree.meta.presetId}`,
    `> Project version: ${projectVersion}`,
    "",
    "## Quick Start",
    "",
    "### CSS Variables",
    "```html",
    `<link rel="stylesheet" href="tokens/tokens_${filenameSuffix}.css">`,
    "```",
    "",
    "### TypeScript",
    "```ts",
    `import { seedTokens, mapTokens, aliasTokens } from "./tokens/tokens_${filenameSuffix}";`,
    "```",
    "",
    "### W3C Design Tokens",
    "```ts",
    `import tokens from "./tokens/tokens_${filenameSuffix}.json";`,
    "```",
    "",
    "## 시스템 구조",
    "",
    "- **Seed**: 디자이너가 직접 결정한 13종 (`tokens.seed.*.json`)",
    "- **Map**: Seed에서 알고리즘으로 파생된 색 11단·사이즈·반경·타이포 스케일",
    "- **Alias**: 컴포넌트가 참조하는 의미 토큰 (모든 컴포넌트는 Alias만 참조)",
    "",
    "## 컴포넌트 목록 (L1 핵심 5종)",
    "",
    "- [Button](components/Button.md)",
    "- [Input](components/Input.md)",
    "- [Card](components/Card.md)",
    "- [Modal](components/Modal.md)",
    "- [Form](components/Form.md)",
    "",
    "## 접근성 준수",
    "",
    "본 디자인 시스템은 WCAG 2.2 AA 및 KWCAG 2.2 두 기준을 점검 대상으로 합니다.",
    `상세 보고서: [guides/accessibility-report_${filenameSuffix}.md](guides/accessibility-report_${filenameSuffix}.md)`,
    "",
    "## 변경하려면",
    "",
    "본 디자인 시스템은 XDS Generator에서 생성되었습니다. 파일을 직접 수정하지 마시고,",
    "도구에서 본 프로젝트를 열어 수정 후 재 export 해주세요.",
    "",
    "- Read-only 원칙: 모든 파일 상단에 `GENERATED BY ... DO NOT EDIT MANUALLY` 표시",
    "- 재 export 시 동일한 파일명 규칙으로 새 버전이 생성됩니다.",
    "",
  ].join("\n");
}
