/**
 * Output Spec §5.3 — tokens.ts (TypeScript 상수·타입) 생성.
 *
 * Seed·Map·Alias를 `as const` 객체로 펼치고, ColorScaleStep·SemanticColor·AliasTextKey 등
 * 도구 사용처에서 자주 쓰이는 union 타입을 자동 export한다.
 */

import {
  COLOR_SCALE_STEPS,
  SEMANTIC_COLORS,
  type TokenTree,
} from "../tokens/types";
import { GENERATOR_VERSION } from "../version";

interface Opts {
  projectName?: string;
  projectVersion?: string;
}

export function tokenTreeToTypeScript(tree: TokenTree, opts: Opts = {}): string {
  const projectName = opts.projectName ?? tree.meta.presetId;
  const projectVersion = opts.projectVersion ?? "1.0.0";
  const lines: string[] = [
    `/* GENERATED BY XDS Generator v${GENERATOR_VERSION} — DO NOT EDIT MANUALLY */`,
    `/* ${projectName} Design System v${projectVersion} — ${tree.meta.derivedAt.slice(0, 10)} */`,
    "",
    "export const seedTokens = {",
    `  color: {`,
    `    primary: ${JSON.stringify(tree.seed.color.primary)},`,
    `    success: ${JSON.stringify(tree.seed.color.success)},`,
    `    warning: ${JSON.stringify(tree.seed.color.warning)},`,
    `    error: ${JSON.stringify(tree.seed.color.error)},`,
    `    info: ${JSON.stringify(tree.seed.color.info)},`,
    `    bgBase: ${JSON.stringify(tree.seed.color.bgBase)},`,
    `    textBase: ${JSON.stringify(tree.seed.color.textBase)},`,
    `  },`,
    `  borderRadius: ${tree.seed.borderRadius},`,
    `  fontSize: ${tree.seed.fontSize},`,
    `  fontFamily: ${JSON.stringify(tree.seed.fontFamily)},`,
    `  spacingBase: ${tree.seed.spacingBase},`,
    `  density: ${JSON.stringify(tree.seed.density)},`,
    `  wireframe: ${tree.seed.wireframe},`,
    ...(tree.seed.onPrimaryColor
      ? [`  onPrimaryColor: ${JSON.stringify(tree.seed.onPrimaryColor)},`]
      : []),
    ...(tree.seed.onDangerColor
      ? [`  onDangerColor: ${JSON.stringify(tree.seed.onDangerColor)},`]
      : []),
    ...(tree.seed.focusRingColorStep
      ? [`  focusRingColorStep: ${JSON.stringify(tree.seed.focusRingColorStep)},`]
      : []),
    ...(tree.seed.actionPrimaryStep
      ? [`  actionPrimaryStep: ${JSON.stringify(tree.seed.actionPrimaryStep)},`]
      : []),
    ...(tree.seed.actionDangerStep
      ? [`  actionDangerStep: ${JSON.stringify(tree.seed.actionDangerStep)},`]
      : []),
    "} as const;",
    "",
    "export const mapTokens = {",
    "  color: {",
  ];

  for (const c of SEMANTIC_COLORS) {
    lines.push(`    ${c}: {`);
    for (const step of COLOR_SCALE_STEPS) {
      lines.push(`      "${step}": ${JSON.stringify(tree.map.color[c][step])},`);
    }
    lines.push(`      default: ${JSON.stringify(tree.map.color[c].default)},`);
    lines.push(`      hover: ${JSON.stringify(tree.map.color[c].hover)},`);
    lines.push(`      active: ${JSON.stringify(tree.map.color[c].active)},`);
    lines.push(`    },`);
  }
  lines.push("  },");

  lines.push("  size: {");
  for (const [k, v] of Object.entries(tree.map.size)) {
    lines.push(`    ${k}: ${v},`);
  }
  lines.push("  },");

  lines.push("  radius: {");
  for (const [k, v] of Object.entries(tree.map.radius)) {
    lines.push(`    ${k}: ${v},`);
  }
  lines.push("  },");

  lines.push("  font: {");
  lines.push("    size: {");
  for (const [k, v] of Object.entries(tree.map.font.size)) {
    lines.push(`      ${k}: ${v},`);
  }
  lines.push("    },");
  lines.push("    lineHeight: {");
  for (const [k, v] of Object.entries(tree.map.font.lineHeight)) {
    lines.push(`      ${k}: ${v},`);
  }
  lines.push("    },");
  lines.push("    letterSpacing: {");
  for (const [k, v] of Object.entries(tree.map.font.letterSpacing)) {
    lines.push(`      ${k}: ${JSON.stringify(v)},`);
  }
  lines.push("    },");
  lines.push("  },");
  lines.push("} as const;");
  lines.push("");

  // Alias — emit raw reference strings, consumers can resolve via tokens.css var().
  lines.push("/** Alias 토큰. 값은 `{map.x.y.z}` 형태의 참조 문자열입니다. */");
  lines.push("export const aliasTokens = {");
  for (const [group, body] of Object.entries({
    text: tree.alias.text,
    surface: tree.alias.surface,
    border: tree.alias.border,
    action: tree.alias.action,
    feedback: tree.alias.feedback,
  })) {
    lines.push(`  ${group}: {`);
    for (const [k, v] of Object.entries(body)) {
      lines.push(`    ${k}: ${JSON.stringify(v)},`);
    }
    lines.push("  },");
  }
  lines.push(`  control: ${JSON.stringify(tree.alias.control)},`);
  lines.push(`  focus: ${JSON.stringify(tree.alias.focus)},`);
  lines.push("} as const;");
  lines.push("");

  lines.push("export type SemanticColor =");
  lines.push(`  | ${SEMANTIC_COLORS.map((c) => JSON.stringify(c)).join(" | ")};`);
  lines.push("export type ColorScaleStep =");
  lines.push(`  | ${COLOR_SCALE_STEPS.map((s) => JSON.stringify(s)).join(" | ")};`);
  lines.push("export type AliasTextKey = keyof typeof aliasTokens.text;");
  lines.push("export type AliasSurfaceKey = keyof typeof aliasTokens.surface;");
  lines.push("export type AliasActionKey = keyof typeof aliasTokens.action;");

  return lines.join("\n") + "\n";
}
