/**
 * Sprint 1A 통합 검증 — Default 프리셋을 실제 디스크에 export.
 *
 * Output Spec §2.2 패키지 구조를 따라 dist-sample/ 하위에 생성한다.
 * v0.1 범위에서는 components·guides·zip 패키징 없이 tokens/* 만 우선 생성.
 *
 * 실행: pnpm demo:export  (또는 npm run demo:export)
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defaultPreset } from "../src/presets/default";
import { tokenTreeToCss } from "../src/output/cssVariables";
import { tokenTreeToW3C } from "../src/output/w3c";
import { generateTokenTree } from "../src/tokens/build";
import { GENERATOR_VERSION } from "../src/version";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(__dirname, "..", "dist-sample");

const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
const projectName = "Sample-Default";
const projectVersion = "1.0.0";
const baseDir = resolve(
  outDir,
  `${projectName}-design-system_v${projectVersion}_${date}`,
);
const tokensDir = resolve(baseDir, "tokens");

mkdirSync(tokensDir, { recursive: true });

const tree = generateTokenTree(defaultPreset);
const css = tokenTreeToCss(tree, { projectName, projectVersion });
const w3c = tokenTreeToW3C(tree, { projectName, projectVersion });

const filenameSuffix = `v${projectVersion}_${date}`;

writeFileSync(
  resolve(tokensDir, `tokens_${filenameSuffix}.css`),
  css,
  "utf8",
);
writeFileSync(
  resolve(tokensDir, `tokens_${filenameSuffix}.json`),
  JSON.stringify(w3c, null, 2),
  "utf8",
);
writeFileSync(
  resolve(tokensDir, `tokens.seed_${filenameSuffix}.json`),
  JSON.stringify({ $metadata: w3c.$metadata, seed: w3c.seed }, null, 2),
  "utf8",
);
writeFileSync(
  resolve(tokensDir, `tokens.map_${filenameSuffix}.json`),
  JSON.stringify({ $metadata: w3c.$metadata, seed: w3c.seed, map: w3c.map }, null, 2),
  "utf8",
);
writeFileSync(
  resolve(tokensDir, `tokens.alias_${filenameSuffix}.json`),
  JSON.stringify({ $metadata: w3c.$metadata, alias: w3c.alias }, null, 2),
  "utf8",
);

const manifest = {
  $schema: "https://xds.xinics.com/schemas/manifest-v1.json",
  generator: {
    name: "XDS Generator",
    version: GENERATOR_VERSION,
    exportedAt: new Date().toISOString(),
  },
  project: {
    id: "proj_sample_default",
    name: projectName,
    type: "admin",
    version: projectVersion,
    createdBy: "Sprint 1A demo",
    createdByVerified: false,
    createdAt: new Date().toISOString(),
  },
  style: {
    preset: defaultPreset.id,
    darkMode: "auto-derived",
    locale: ["ko"],
    locale_structure_ready_for: [],
  },
  files: [
    { path: `tokens/tokens_${filenameSuffix}.css`, type: "tokens", version: projectVersion },
    { path: `tokens/tokens_${filenameSuffix}.json`, type: "tokens", version: projectVersion },
    { path: `tokens/tokens.seed_${filenameSuffix}.json`, type: "tokens", version: projectVersion },
    { path: `tokens/tokens.map_${filenameSuffix}.json`, type: "tokens", version: projectVersion },
    { path: `tokens/tokens.alias_${filenameSuffix}.json`, type: "tokens", version: projectVersion },
  ],
  components: { core: 0, domain: 0, total: 0 },
  dependencies: {
    fontStack: defaultPreset.seed.fontFamily,
    iconLibrary: "lucide-react",
  },
  note:
    "Sprint 1A demo export — components·guides·accessibility report·zip은 v0.1 MVP 범위(Sprint 1B~1D)에서 추가됩니다.",
};

writeFileSync(
  resolve(baseDir, "manifest.json"),
  JSON.stringify(manifest, null, 2),
  "utf8",
);

const readme = `# ${projectName} Design System

> Generated by XDS Generator v${GENERATOR_VERSION} on ${new Date().toISOString()}
> Project type: admin
> Style preset: ${defaultPreset.name} (\`${defaultPreset.id}\`)

## Quick Start

\`\`\`html
<link rel="stylesheet" href="tokens/tokens_${filenameSuffix}.css">
\`\`\`

## 상태

Sprint 1A 데모 export입니다. 컴포넌트 명세·UX 가이드·접근성 보고서·zip 패키지는
Sprint 1B~1D(v0.1 MVP)에서 추가됩니다.

## 변경하려면

본 산출물은 XDS Generator로 생성되었습니다. 직접 파일을 수정하지 마시고,
도구에서 프로젝트를 열어 수정 후 재 export 해주세요.
`;
writeFileSync(resolve(baseDir, "README.md"), readme, "utf8");

console.log(`✓ Sample export created at: ${baseDir}`);
console.log(`  tokens.css : ${css.split("\n").length} lines`);
console.log(`  tokens.json: ${Object.keys(w3c.map).length} map sections`);
console.log("");
console.log("Sprint 1A 통합 동작 검증 완료.");
