/**
 * Token Tree 빌드 통합 테스트 — Default 프리셋이 W3C JSON·CSS Variables로
 * 변환되는 전 과정이 회귀하지 않음을 보장한다 (Sprint 1A T-007).
 */

import { describe, expect, it } from "vitest";
import { defaultPreset } from "../../presets/default";
import { tokenTreeToCss } from "../../output/cssVariables";
import { parseSeedFromW3C, tokenTreeToW3C } from "../../output/w3c";
import { generateTokenTree } from "../build";

describe("Default 프리셋 → TokenTree", () => {
  const tree = generateTokenTree(defaultPreset);

  it("Seed 13종이 그대로 전달된다", () => {
    expect(tree.seed.color.primary).toBe(defaultPreset.seed.color.primary);
    expect(tree.seed.borderRadius).toBe(6);
    expect(tree.seed.density).toBe("default");
  });

  it("Map 색상 6종 × 11단 = 66 + 상태 변형이 모두 생성", () => {
    expect(Object.keys(tree.map.color.primary)).toHaveLength(21);
  });

  it("Alias가 토큰 참조 문자열을 갖는다 (map.* 또는 seed.*)", () => {
    expect(tree.alias.text.body).toMatch(/^\{map\./);
    // action.primary는 seed.color.primary를 직접 가리키는 게 기본 (사용자가 Primary
    // Color picker로 고른 색이 곧 버튼 색). 사용자가 actionPrimaryStep을 명시하면
    // {map.color.primary.${step}}으로 전환된다.
    expect(tree.alias.action.primary).toMatch(/^\{(map|seed)\./);
  });
});

describe("CSS Variables 시리얼라이저", () => {
  const tree = generateTokenTree(defaultPreset);
  const css = tokenTreeToCss(tree);

  it("read-only 헤더가 포함된다", () => {
    expect(css).toMatch(/GENERATED BY XDS Generator/);
    expect(css).toMatch(/DO NOT EDIT MANUALLY/);
  });

  it(":root 블록이 있다", () => {
    expect(css).toMatch(/:root \{/);
  });

  it("Seed·Map·Alias가 모두 펼쳐진다", () => {
    expect(css).toMatch(/--xds-seed-color-primary:/);
    expect(css).toMatch(/--xds-color-primary-500:/);
    expect(css).toMatch(/--xds-text-body:/);
  });

  it("prefers-reduced-motion 미디어 쿼리가 있다 (a11y O-12)", () => {
    expect(css).toMatch(/@media \(prefers-reduced-motion: reduce\)/);
  });
});

describe("W3C 시리얼라이저 ↔ 파서 round-trip", () => {
  const tree = generateTokenTree(defaultPreset);
  const doc = tokenTreeToW3C(tree);

  it("$schema·$metadata가 포함된다", () => {
    expect(doc.$schema).toMatch(/design-tokens/);
    expect(doc.$metadata.generatorVersion).toBeTruthy();
  });

  it("Seed 토큰이 $value·$type을 갖는다", () => {
    const primaryToken = (doc.seed as { color: { primary: { $value: string; $type: string } } })
      .color.primary;
    expect(primaryToken.$value).toBe(defaultPreset.seed.color.primary);
    expect(primaryToken.$type).toBe("color");
  });

  it("Seed가 round-trip 손실 없이 복원된다", () => {
    const restored = parseSeedFromW3C(doc);
    expect(restored).not.toBeNull();
    expect(restored!.color.primary).toBe(defaultPreset.seed.color.primary);
    expect(restored!.borderRadius).toBe(defaultPreset.seed.borderRadius);
    expect(restored!.fontFamily).toEqual(defaultPreset.seed.fontFamily);
  });
});
